version: '3.8'

services:
  app:
    container_name: my-node-app
    image: node:22.17-alpine3.21
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start:prod
    network_mode: host
